### PR TITLE
Upload data to artipost

### PR DESCRIPTION
**Pull request by filoozom**

### CODE REVIEW

**Comment by artipost** [comment]
Artifacts:
- [file1.zip](https://gist.githubusercontent.com/artipost/f1520a80357fd59ddae987d360712c22/raw/9e0f96a2a253b173cb45b41868209a5d043e1437/file1.zip)
- [file2.zip](https://gist.githubusercontent.com/artipost/f1520a80357fd59ddae987d360712c22/raw/3301331bed0971ef2a52684ad73baa99ed523573/file2.zip)

**Comment by artipost** [comment]
Files: [file1.zip], [file2.zip]

**Comment by artipost** [comment]
Files: [file1.zip(https://gist.githubusercontent.com/artipost/f63c8c71fa93d82e0f61135eff3e5982/raw/9e0f96a2a253b173cb45b41868209a5d043e1437/file1.zip)], [file2.zip(https://gist.githubusercontent.com/artipost/f63c8c71fa93d82e0f61135eff3e5982/raw/3301331bed0971ef2a52684ad73baa99ed523573/file2.zip)]

**Comment by artipost** [comment]
Files: [file1.zip](https://gist.githubusercontent.com/artipost/42c2545743560bbaf32f398ad73cb838/raw/9e0f96a2a253b173cb45b41868209a5d043e1437/file1.zip), [file2.zip](https://gist.githubusercontent.com/artipost/42c2545743560bbaf32f398ad73cb838/raw/3301331bed0971ef2a52684ad73baa99ed523573/file2.zip)

**Comment by artipost** [comment]
Files: [file1.zip](https://gist.githubusercontent.com/artipost/afcfadfbf9f2cf802551c0e2d31243d8/raw/9e0f96a2a253b173cb45b41868209a5d043e1437/file1.zip), [file2.zip](https://gist.githubusercontent.com/artipost/afcfadfbf9f2cf802551c0e2d31243d8/raw/3301331bed0971ef2a52684ad73baa99ed523573/file2.zip)

##
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [357356762](https://travis-ci.org/filoozom/cipost-test-repo/builds/357356762), for commit [bb74126](https://github.com/filoozom/cipost-test-repo/pull/1/commits/bb7412686368dd7fe253a61a62ae57f86d228e31).

**Comment by filoozom** [comment]
Files: [file1.zip](https://gist.githubusercontent.com/artipost/afcfadfbf9f2cf802551c0e2d31243d8/raw/9e0f96a2a253b173cb45b41868209a5d043e1437/file1.zip), [file2.zip](https://gist.githubusercontent.com/artipost/afcfadfbf9f2cf802551c0e2d31243d8/raw/3301331bed0971ef2a52684ad73baa99ed523573/file2.zip)

---
:postbox: Posted by [artipost.io](https://artipost.io), through Travis build [357356762](https://travis-ci.org/filoozom/cipost-test-repo/builds/357356762), for commit [bb74126](https://github.com/filoozom/cipost-test-repo/pull/1/commits/bb7412686368dd7fe253a61a62ae57f86d228e31).

**Pull request closed without merging**
